import mongoose from "mongoose"
import dotenv from "dotenv"
import Product from "./models/Product"

dotenv.config()

// product data scraped from dummyJSON
const products = [
    {
        "id": 1,
        "title": "Essence Mascara Lash Princess",
        "description": "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        "category": "beauty",
        "price": 9.99,
        "rating": 2.56,
        "brand": "Essence",
        "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 week warranty",
        "stock": 99
    },
    {
        "id": 2,
        "title": "Eyeshadow Palette with Mirror",
        "description": "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
        "category": "beauty",
        "price": 19.99,
        "rating": 2.86,
        "brand": "Glamour Beauty",
        "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 year warranty",
        "stock": 34
    },
    {
        "id": 3,
        "title": "Powder Canister",
        "description": "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
        "category": "beauty",
        "price": 14.99,
        "rating": 4.64,
        "brand": "Velvet Touch",
        "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 months warranty",
        "stock": 89
    },
    {
        "id": 4,
        "title": "Red Lipstick",
        "description": "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
        "category": "beauty",
        "price": 12.99,
        "rating": 4.36,
        "brand": "Chic Cosmetics",
        "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 year warranty",
        "stock": 91
    },
    {
        "id": 5,
        "title": "Red Nail Polish",
        "description": "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
        "category": "beauty",
        "price": 8.99,
        "rating": 4.32,
        "brand": "Nail Couture",
        "thumbnail": "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 month warranty",
        "stock": 79
    },
    {
        "id": 6,
        "title": "Calvin Klein CK One",
        "description": "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
        "category": "fragrances",
        "price": 49.99,
        "rating": 4.37,
        "brand": "Calvin Klein",
        "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 week warranty",
        "stock": 29
    },
    {
        "id": 7,
        "title": "Chanel Coco Noir Eau De",
        "description": "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
        "category": "fragrances",
        "price": 129.99,
        "rating": 4.26,
        "brand": "Chanel",
        "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 year warranty",
        "stock": 58
    },
    {
        "id": 8,
        "title": "Dior J'adore",
        "description": "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
        "category": "fragrances",
        "price": 89.99,
        "rating": 3.8,
        "brand": "Dior",
        "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 week warranty",
        "stock": 98
    },
    {
        "id": 9,
        "title": "Dolce Shine Eau de",
        "description": "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
        "category": "fragrances",
        "price": 69.99,
        "rating": 3.96,
        "brand": "Dolce & Gabbana",
        "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp",
        "availabilityStatus": "Low Stock",
        "warrantyInformation": "3 year warranty",
        "stock": 4
    },
    {
        "id": 10,
        "title": "Gucci Bloom Eau de",
        "description": "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
        "category": "fragrances",
        "price": 79.99,
        "rating": 2.74,
        "brand": "Gucci",
        "thumbnail": "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "6 months warranty",
        "stock": 91
    },
    {
        "id": 11,
        "title": "Annibale Colombo Bed",
        "description": "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
        "category": "furniture",
        "price": 1899.99,
        "rating": 4.77,
        "brand": "Annibale Colombo",
        "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 year warranty",
        "stock": 88
    },
    {
        "id": 12,
        "title": "Annibale Colombo Sofa",
        "description": "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
        "category": "furniture",
        "price": 2499.99,
        "rating": 3.92,
        "brand": "Annibale Colombo",
        "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "Lifetime warranty",
        "stock": 60
    },
    {
        "id": 13,
        "title": "Bedside Table African Cherry",
        "description": "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
        "category": "furniture",
        "price": 299.99,
        "rating": 2.87,
        "brand": "Furniture Co.",
        "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "5 year warranty",
        "stock": 64
    },
    {
        "id": 14,
        "title": "Knoll Saarinen Executive Conference Chair",
        "description": "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
        "category": "furniture",
        "price": 499.99,
        "rating": 4.88,
        "brand": "Knoll",
        "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "2 year warranty",
        "stock": 26
    },
    {
        "id": 15,
        "title": "Wooden Bathroom Sink With Mirror",
        "description": "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
        "category": "furniture",
        "price": 799.99,
        "rating": 3.59,
        "brand": "Bath Trends",
        "thumbnail": "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp",
        "availabilityStatus": "Low Stock",
        "warrantyInformation": "3 year warranty",
        "stock": 7
    },
    {
        "id": 16,
        "title": "Apple",
        "description": "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
        "category": "groceries",
        "price": 1.99,
        "rating": 4.19,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 year warranty",
        "stock": 8
    },
    {
        "id": 17,
        "title": "Beef Steak",
        "description": "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
        "category": "groceries",
        "price": 12.99,
        "rating": 4.47,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 year warranty",
        "stock": 86
    },
    {
        "id": 18,
        "title": "Cat Food",
        "description": "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
        "category": "groceries",
        "price": 8.99,
        "rating": 3.13,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 year warranty",
        "stock": 46
    },
    {
        "id": 19,
        "title": "Chicken Meat",
        "description": "Fresh and tender chicken meat, suitable for various culinary preparations.",
        "category": "groceries",
        "price": 9.99,
        "rating": 3.19,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 year warranty",
        "stock": 97
    },
    {
        "id": 20,
        "title": "Cooking Oil",
        "description": "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.",
        "category": "groceries",
        "price": 4.99,
        "rating": 4.8,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "Lifetime warranty",
        "stock": 10
    },
    {
        "id": 21,
        "title": "Cucumber",
        "description": "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
        "category": "groceries",
        "price": 1.49,
        "rating": 4.07,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "2 year warranty",
        "stock": 84
    },
    {
        "id": 22,
        "title": "Dog Food",
        "description": "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
        "category": "groceries",
        "price": 10.99,
        "rating": 4.55,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "No warranty",
        "stock": 71
    },
    {
        "id": 23,
        "title": "Eggs",
        "description": "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
        "category": "groceries",
        "price": 2.99,
        "rating": 2.53,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 week warranty",
        "stock": 9
    },
    {
        "id": 24,
        "title": "Fish Steak",
        "description": "Quality fish steak, suitable for grilling, baking, or pan-searing.",
        "category": "groceries",
        "price": 14.99,
        "rating": 3.78,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 month warranty",
        "stock": 74
    },
    {
        "id": 25,
        "title": "Green Bell Pepper",
        "description": "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
        "category": "groceries",
        "price": 1.29,
        "rating": 3.25,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 month warranty",
        "stock": 33
    },
    {
        "id": 26,
        "title": "Green Chili Pepper",
        "description": "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
        "category": "groceries",
        "price": 0.99,
        "rating": 3.66,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp",
        "availabilityStatus": "Low Stock",
        "warrantyInformation": "2 year warranty",
        "stock": 3
    },
    {
        "id": 27,
        "title": "Honey Jar",
        "description": "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
        "category": "groceries",
        "price": 6.99,
        "rating": 3.97,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 month warranty",
        "stock": 34
    },
    {
        "id": 28,
        "title": "Ice Cream",
        "description": "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
        "category": "groceries",
        "price": 5.49,
        "rating": 3.39,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 month warranty",
        "stock": 27
    },
    {
        "id": 29,
        "title": "Juice",
        "description": "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
        "category": "groceries",
        "price": 3.99,
        "rating": 3.94,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "6 months warranty",
        "stock": 50
    },
    {
        "id": 30,
        "title": "Kiwi",
        "description": "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
        "category": "groceries",
        "price": 2.49,
        "rating": 4.93,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "6 months warranty",
        "stock": 99
    },
    {
        "id": 31,
        "title": "Lemon",
        "description": "Zesty and tangy lemons, versatile for cooking, baking, or making refreshing beverages.",
        "category": "groceries",
        "price": 0.79,
        "rating": 3.53,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/lemon/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "No warranty",
        "stock": 31
    },
    {
        "id": 32,
        "title": "Milk",
        "description": "Fresh and nutritious milk, a staple for various recipes and daily consumption.",
        "category": "groceries",
        "price": 3.49,
        "rating": 2.61,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/milk/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 year warranty",
        "stock": 27
    },
    {
        "id": 33,
        "title": "Mulberry",
        "description": "Sweet and juicy mulberries, perfect for snacking or adding to desserts and cereals.",
        "category": "groceries",
        "price": 4.99,
        "rating": 4.95,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/mulberry/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "2 year warranty",
        "stock": 99
    },
    {
        "id": 34,
        "title": "Nescafe Coffee",
        "description": "Quality coffee from Nescafe, available in various blends for a rich and satisfying cup.",
        "category": "groceries",
        "price": 7.99,
        "rating": 4.82,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/nescafe-coffee/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 year warranty",
        "stock": 57
    },
    {
        "id": 35,
        "title": "Potatoes",
        "description": "Versatile and starchy potatoes, great for roasting, mashing, or as a side dish.",
        "category": "groceries",
        "price": 2.29,
        "rating": 4.81,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 year warranty",
        "stock": 13
    },
    {
        "id": 36,
        "title": "Protein Powder",
        "description": "Nutrient-packed protein powder, ideal for supplementing your diet with essential proteins.",
        "category": "groceries",
        "price": 19.99,
        "rating": 4.18,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/protein-powder/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 week warranty",
        "stock": 80
    },
    {
        "id": 37,
        "title": "Red Onions",
        "description": "Flavorful and aromatic red onions, perfect for adding depth to your savory dishes.",
        "category": "groceries",
        "price": 1.99,
        "rating": 4.2,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/red-onions/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 month warranty",
        "stock": 82
    },
    {
        "id": 38,
        "title": "Rice",
        "description": "High-quality rice, a staple for various cuisines and a versatile base for many dishes.",
        "category": "groceries",
        "price": 5.99,
        "rating": 3.18,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/rice/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "6 months warranty",
        "stock": 59
    },
    {
        "id": 39,
        "title": "Soft Drinks",
        "description": "Assorted soft drinks in various flavors, perfect for refreshing beverages.",
        "category": "groceries",
        "price": 1.99,
        "rating": 4.75,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "6 months warranty",
        "stock": 53
    },
    {
        "id": 40,
        "title": "Strawberry",
        "description": "Sweet and succulent strawberries, great for snacking, desserts, or blending into smoothies.",
        "category": "groceries",
        "price": 3.99,
        "rating": 3.08,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/strawberry/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 week warranty",
        "stock": 46
    },
    {
        "id": 41,
        "title": "Tissue Paper Box",
        "description": "Convenient tissue paper box for everyday use, providing soft and absorbent tissues.",
        "category": "groceries",
        "price": 2.49,
        "rating": 2.69,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "No warranty",
        "stock": 86
    },
    {
        "id": 42,
        "title": "Water",
        "description": "Pure and refreshing bottled water, essential for staying hydrated throughout the day.",
        "category": "groceries",
        "price": 0.99,
        "rating": 4.96,
        "thumbnail": "https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 months warranty",
        "stock": 53
    },
    {
        "id": 43,
        "title": "Decoration Swing",
        "description": "The Decoration Swing is a charming addition to your home decor. Crafted with intricate details, it adds a touch of elegance and whimsy to any room.",
        "category": "home-decoration",
        "price": 59.99,
        "rating": 3.16,
        "thumbnail": "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 week warranty",
        "stock": 47
    },
    {
        "id": 44,
        "title": "Family Tree Photo Frame",
        "description": "The Family Tree Photo Frame is a sentimental and stylish way to display your cherished family memories. With multiple photo slots, it tells the story of your loved ones.",
        "category": "home-decoration",
        "price": 29.99,
        "rating": 4.53,
        "thumbnail": "https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 month warranty",
        "stock": 77
    },
    {
        "id": 45,
        "title": "House Showpiece Plant",
        "description": "The House Showpiece Plant is an artificial plant that brings a touch of nature to your home without the need for maintenance. It adds greenery and style to any space.",
        "category": "home-decoration",
        "price": 39.99,
        "rating": 4.67,
        "thumbnail": "https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 year warranty",
        "stock": 28
    },
    {
        "id": 46,
        "title": "Plant Pot",
        "description": "The Plant Pot is a stylish container for your favorite plants. With a sleek design, it complements your indoor or outdoor garden, adding a modern touch to your plant display.",
        "category": "home-decoration",
        "price": 14.99,
        "rating": 3.01,
        "thumbnail": "https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "Lifetime warranty",
        "stock": 59
    },
    {
        "id": 47,
        "title": "Table Lamp",
        "description": "The Table Lamp is a functional and decorative lighting solution for your living space. With a modern design, it provides both ambient and task lighting, enhancing the atmosphere.",
        "category": "home-decoration",
        "price": 49.99,
        "rating": 3.55,
        "thumbnail": "https://cdn.dummyjson.com/product-images/home-decoration/table-lamp/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 months warranty",
        "stock": 9
    },
    {
        "id": 48,
        "title": "Bamboo Spatula",
        "description": "The Bamboo Spatula is a versatile kitchen tool made from eco-friendly bamboo. Ideal for flipping, stirring, and serving various dishes.",
        "category": "kitchen-accessories",
        "price": 7.99,
        "rating": 3.27,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/bamboo-spatula/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 month warranty",
        "stock": 37
    },
    {
        "id": 49,
        "title": "Black Aluminium Cup",
        "description": "The Black Aluminium Cup is a stylish and durable cup suitable for both hot and cold beverages. Its sleek black design adds a modern touch to your drinkware collection.",
        "category": "kitchen-accessories",
        "price": 5.99,
        "rating": 4.46,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/black-aluminium-cup/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 year warranty",
        "stock": 75
    },
    {
        "id": 50,
        "title": "Black Whisk",
        "description": "The Black Whisk is a kitchen essential for whisking and beating ingredients. Its ergonomic handle and sleek design make it a practical and stylish tool.",
        "category": "kitchen-accessories",
        "price": 9.99,
        "rating": 3.9,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 months warranty",
        "stock": 73
    },
    {
        "id": 51,
        "title": "Boxed Blender",
        "description": "The Boxed Blender is a powerful and compact blender perfect for smoothies, shakes, and more. Its convenient design and multiple functions make it a versatile kitchen appliance.",
        "category": "kitchen-accessories",
        "price": 39.99,
        "rating": 4.56,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "5 year warranty",
        "stock": 9
    },
    {
        "id": 52,
        "title": "Carbon Steel Wok",
        "description": "The Carbon Steel Wok is a versatile cooking pan suitable for stir-frying, sautéing, and deep frying. Its sturdy construction ensures even heat distribution for delicious meals.",
        "category": "kitchen-accessories",
        "price": 29.99,
        "rating": 4.05,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/carbon-steel-wok/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "2 year warranty",
        "stock": 40
    },
    {
        "id": 53,
        "title": "Chopping Board",
        "description": "The Chopping Board is an essential kitchen accessory for food preparation. Made from durable material, it provides a safe and hygienic surface for cutting and chopping.",
        "category": "kitchen-accessories",
        "price": 12.99,
        "rating": 3.7,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/chopping-board/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 months warranty",
        "stock": 14
    },
    {
        "id": 54,
        "title": "Citrus Squeezer Yellow",
        "description": "The Citrus Squeezer in Yellow is a handy tool for extracting juice from citrus fruits. Its vibrant color adds a cheerful touch to your kitchen gadgets.",
        "category": "kitchen-accessories",
        "price": 8.99,
        "rating": 4.63,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/citrus-squeezer-yellow/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "2 year warranty",
        "stock": 22
    },
    {
        "id": 55,
        "title": "Egg Slicer",
        "description": "The Egg Slicer is a convenient tool for slicing boiled eggs evenly. It's perfect for salads, sandwiches, and other dishes where sliced eggs are desired.",
        "category": "kitchen-accessories",
        "price": 6.99,
        "rating": 3.09,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/egg-slicer/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 week warranty",
        "stock": 40
    },
    {
        "id": 56,
        "title": "Electric Stove",
        "description": "The Electric Stove provides a portable and efficient cooking solution. Ideal for small kitchens or as an additional cooking surface for various culinary needs.",
        "category": "kitchen-accessories",
        "price": 49.99,
        "rating": 4.11,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "2 year warranty",
        "stock": 21
    },
    {
        "id": 57,
        "title": "Fine Mesh Strainer",
        "description": "The Fine Mesh Strainer is a versatile tool for straining liquids and sifting dry ingredients. Its fine mesh ensures efficient filtering for smooth cooking and baking.",
        "category": "kitchen-accessories",
        "price": 9.99,
        "rating": 3.04,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/fine-mesh-strainer/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 month warranty",
        "stock": 85
    },
    {
        "id": 58,
        "title": "Fork",
        "description": "The Fork is a classic utensil for various dining and serving purposes. Its durable and ergonomic design makes it a reliable choice for everyday use.",
        "category": "kitchen-accessories",
        "price": 3.99,
        "rating": 3.11,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/fork/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "No warranty",
        "stock": 7
    },
    {
        "id": 59,
        "title": "Glass",
        "description": "The Glass is a versatile and elegant drinking vessel suitable for a variety of beverages. Its clear design allows you to enjoy the colors and textures of your drinks.",
        "category": "kitchen-accessories",
        "price": 4.99,
        "rating": 4.02,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/glass/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "3 year warranty",
        "stock": 46
    },
    {
        "id": 60,
        "title": "Grater Black",
        "description": "The Grater in Black is a handy kitchen tool for grating cheese, vegetables, and more. Its sleek design and sharp blades make food preparation efficient and easy.",
        "category": "kitchen-accessories",
        "price": 10.99,
        "rating": 3.21,
        "thumbnail": "https://cdn.dummyjson.com/product-images/kitchen-accessories/grater-black/thumbnail.webp",
        "availabilityStatus": "In Stock",
        "warrantyInformation": "1 month warranty",
        "stock": 84
    }
]

// utiity to add scraped data from DummyJSON to MDB
async function seedProducts() {
    try {
        await mongoose.connect(process.env.MONGO_URI)
        await Product.deleteMany()
        const result = await Product.insertMany(products)
        console.log("Seeding successful:", result)
    } catch (err) {
        console.error("Seeding error:", err)
    }
}

seedProducts()